name: SkyblockX
main: net.savagelabs.skyblockx.SkyblockX
version: 1.5.2
api-version: '1.13'
load: POSTWORLD
depend: [XCore]
softdepend: [PlaceholderAPI, ShopGUIPlus, WildStacker]
loadbefore: [Multiverse-Core]
authors: [ProSavage, Zed]
description: 'The Ultimate Skyblock Core'
commands:
  skyblockx:
    description: 'base skyblock command'
    aliases: [skyblock, sskyblock, sb, sbx, sblock]
  is:
    description: 'base island command'
    aliases: [island]
