name: SkyblockX
main: net.savagelabs.skyblockx.SkyblockX
version: 1.5
api-version: '1.13'
load: POSTWORLD
softdepend: [PlaceholderAPI]
loadbefore: [Multiverse-Core]
authors: [ProSavage]
description: 'The Ultimate Skyblock Core'
commands:
  skyblockx:
    description: 'base skyblock command'
    aliases: [skyblock, sskyblock, sb, sbx, sblock]
  is:
    description: 'base island command'
    aliases: [island]
