name: Wiki Updater
on: [push]
jobs:
  update-permission-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew clean updatePermissionsList
      - uses: awact/wiki-action@master
        env:
          ACTION_MAIL: naman0311@gmail.com
          ACTION_NAME: ProSavage
          GH_PAT: ${{ secrets.GH_PAT }}
          MD_FOLDER: Wiki
          OWNER: illyria-io
          REPO_NAME: SkyblockX
